default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
exclude: |
  (?x)(
      ^assets/|
      ^docs/.*.html|
      ^inst/extdata|
      ^man/|
      ^tests/testthat/_snaps/|
      ^CITATION.cff|
      ^renv*|
      ^.*.svg|
      ^_extension/|
      ^_freeze/
   )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=12000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # spell check
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["-I ./.github/codespell-ignore"]
  # R formatting
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
      - id: parsable-R
      - id: use-tidy-description
      - id: lintr
        args: [--warn_only]
        verbose: true
  # Python formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  # enforce commit format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
